### ISSUE TITLE
Session Cookies

### ISSUE THREAD

**Issue by digitalassassins** [cubiclesoft/ultimate-web-scraper#7] opened 2017-09-27 11:22 UTC
Trying to scrape a website and the external server responds with a 1 hour old cookie and a message stating:

Session Expired.

Ive tried to set the cookies using SetCookies and also checked the server time to see if there is a problem with the browser emulating the server time. 
Server is set to +0GMT but still the Server responds with an expired cookie. Is this to do with the Web Browser emulation class. Where can i find to manipulate the Cookie expires time or set the WebBrowser Emulation Time ?

**Comment by digitalassassins** [comment] 2017-09-27 12:24
worked out the server uses the following code in javascript to set the cookies:

```
function setCookie(t,e,i){
var n=t+"="+e+"; 
path=/";
if(i){
var o=new Date;
o.setTime(o.getTime()+24*i*60*60*1e3),n=n+";
expires="+o.toGMTString()
}
"https:"==document.location.protocol&&(n+="; Secure"),
document.cookie=n}

function getCookie(t){for(var e=t+"=",i=document.cookie.split(";"),n=0,o=i.length;o>n;n++)
{for(var s=i[n];" "==s.charAt(0);)s=s.substring(1,s.length);if(0===s.indexOf(e))return s.substring(e.length,s.length)}return null}
```

so the problem doesnt seem to be with the actual PHP. the Javascript is being ran by the PHP file but for some reason Javascript time seems to be an hour behind on the server. Would you recommend using PhantomJS to solve this problem ? The form is working fine in my standard web browser.

**Comment by cubiclesoft** [comment] 2017-09-29 03:19
The `WebBrowser::SetCookie()` function takes in an array of information and sets the internal cookie state.  It expects a certain standardized notation and will return an error if anything important is missing.  You should dump its output to make sure that it is not returning an error.

The Javascript functions you see there seem to be fairly standard setCookie/getCookie functions.  You will note that `i` in the setCookie function you provided above is optional and, when not supplied, such cookies will have no expiration date/time.

I recommend carefully watching the cookies that are sent to the server to determine which ones you are NOT sending.  Setting `debug` to `true` in the `$options` array you pass to the `WebBrowser::Process()` function is the most precise way to tell you what the request is that is being sent to the server as it returns a raw data dump byte-for-byte of what was sent and received.  Compare the raw data sent to the server to the headers sent by your web browser (under Developer Tools -> Network tab in most browsers).

When a server responds with an outdated cookie and a session timeout message, that's usually an indicator that they are intentionally setting an expired cookie because you sent wrong or missing information.

You can probably avoid resorting to PhantomJS at this point.

**Comment by cubiclesoft** [comment] 2017-10-04 01:45
Closing this issue as it hasn't been confirmed to be a bug in the software and you found the forums.

**Closed as completed by cubiclesoft** 2017-10-04 01:45 UTC
