### ISSUE TITLE
How can I set up a proxy?

### ISSUE THREAD

**Issue by yoandrygc** [cubiclesoft/ultimate-web-scraper#1] opened 2015-04-01 11:35 UTC
I would like to know how to setup a proxy in the different scenarios that can happen.

**Comment by cubiclesoft** [comment] 2015-04-06 06:35
The official support channel for this project is here:

http://barebonescms.com/forums/

Closing this issue as it is not a bug in the product.

**Closed as completed by cubiclesoft** 2015-04-06 06:35 UTC
