### ISSUE TITLE
How to scrape content within a class

### ISSUE THREAD

**Issue by samdi** [cubiclesoft/ultimate-web-scraper#37] opened 2023-03-16 15:23 UTC
`<body class="article-template main-page articleid-1625 bg-black text-lg" data-content="" data-uid="653263">`

I try to extract the article id number `1625` and `data-uid` but getting errors. Thanks!

**Comment by DrLightman** [comment] 2023-03-17 13:54
Hi, congrats you nailed the perfect "how not to write a support request"

**Comment by cubiclesoft** [comment] 2023-03-17 14:21
@DrLightman While issue trackers are the wrong place to ask for assistance (Discord is better), please stick to constructive, positive responses.  Thank you.

To answer the question, classes are extracted for you by the TagFilter library into an array.  Accessing hyphenated names when they are attributes is also a tad tricky in PHP.  Here's some sample code:

```php
...

$row = $root->Find("body")->current();

foreach ($row->class as $key => $val)
{
  if (substr($key, 0, 10) === "articleid-")  echo substr($key, 10) . "\n";
}

echo $row->{"data-uid"} . "\n";
```

That should hopefully extract what you are looking for.

Since this is not a bug in this library, I'm closing the issue.

**Closed as completed by cubiclesoft** 2023-03-17 14:21 UTC
